import { branchName } from "./identity";
import { git, scrub } from "./repo";

export { branchName };

export type PrEvidence = {
  repoFullName: string;
  runId: string;
  jobName: string;
  buildNumber: number;
  buildUrl?: string;
  commitSha: string;
  testClass: string;
  testName: string;
  file: string;
  constantName: string;
  oldXpath: string;
  newXpath: string;
  strategy: "deterministic" | "ai";
  provider?: string;
  model?: string;
  rationale?: string;
  matchCount: number;
  redTests: string;
  greenTests: string;
  changedLines: number;
};

/** The evidence a human needs to approve or reject in about twenty seconds. */
export function prBody(e: PrEvidence): string {
  const model = e.strategy === "ai" ? `${e.provider} · ${e.model}` : "no model call";
  return `## Automated XPath heal — human review required

| | |
|---|---|
| **Was** | \`${e.oldXpath}\` |
| **Now** | \`${e.newXpath}\` |
| **Constant** | \`${e.constantName}\` |
| **File** | \`${e.file}\` |
| **Strategy** | ${e.strategy} (${model}) |
| **Test** | \`${e.testClass}.${e.testName}\` |
| **Build** | ${e.buildUrl ? `[${e.jobName}#${e.buildNumber}](${e.buildUrl})` : `${e.jobName}#${e.buildNumber}`} |
| **Commit** | \`${e.commitSha}\` |

${e.rationale ? `**Why this anchor:** ${e.rationale}\n` : ""}
### Verification

- ✅ Candidate matched exactly **${e.matchCount}** element in the DOM captured at failure
- ✅ **RED** — unpatched \`${e.commitSha.slice(0, 7)}\` reproduced the failure (${e.redTests})
- ✅ **GREEN** — patched branch passed the full suite (${e.greenTests})
- ✅ Diff touches 1 file, ${e.changedLines} line(s), a locator constant only
- ✅ No test, assertion, build or CI file changed

> Generated by xpath_healer · run \`${e.runId}\`
> A green suite is not proof of a correct locator: check that the new XPath targets the
> element the test means, not merely an element that satisfies the assertions.`;
}

/** Commit, push the branch, and open the PR. Never pushes to the base branch. */
export async function openPullRequest(dir: string, e: PrEvidence): Promise<string> {
  const branch = branchName(e);
  const base = process.env.HEAL_BASE_BRANCH ?? "main";

  await git(dir, "config", "user.name", "xpath-healer[bot]");
  await git(dir, "config", "user.email", "xpath-healer@users.noreply.github.com");
  await git(dir, "checkout", "-q", "-b", branch);
  await git(dir, "add", e.file);
  await git(
    dir,
    "commit",
    "-q",
    "-m",
    `fix(locators): heal ${e.constantName} after markup change\n\n` +
      `${e.jobName}#${e.buildNumber} · run ${e.runId}\n` +
      `Was:  ${e.oldXpath}\nNow:  ${e.newXpath}\n\n` +
      `Opened by xpath_healer. Review before merging.`,
  );
  await git(dir, "push", "-q", "-u", "origin", branch);

  const response = await fetch(`https://api.github.com/repos/${e.repoFullName}/pulls`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${process.env.GITHUB_TOKEN}`,
      Accept: "application/vnd.github+json",
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      title: `Heal ${e.constantName} (${e.jobName}#${e.buildNumber})`,
      head: branch,
      base,
      body: prBody(e),
      // Draft would hide it from reviewers' queues; this needs a human, visibly.
      draft: false,
    }),
  });

  const json = (await response.json()) as { html_url?: string; message?: string };
  if (!response.ok || !json.html_url) {
    throw new Error(scrub(`GitHub refused the PR: ${response.status} ${json.message}`));
  }

  // Labels are best-effort: a missing label must not fail a verified heal.
  await fetch(
    `https://api.github.com/repos/${e.repoFullName}/issues/${json.html_url.split("/").pop()}/labels`,
    {
      method: "POST",
      headers: {
        Authorization: `Bearer ${process.env.GITHUB_TOKEN}`,
        Accept: "application/vnd.github+json",
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ labels: ["automated", "xpath-heal"] }),
    },
  ).catch(() => {});

  return json.html_url;
}

/** A rejected candidate must not leave a branch behind. */
export async function deleteBranch(dir: string, branch: string) {
  await git(dir, "push", "-q", "origin", "--delete", branch).catch(() => {});
}
